driver:
  name: dokken
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd

  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default-chef12
    driver:
      chef_version: 12
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/integration/default

  - name: default-chef13
    driver:
      chef_version: 13
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/integration/default

  - name: default-chef14
    driver:
      chef_version: 14
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/integration/default
